puts 'I met a butterfly the other day.'
puts 'I was just hanging out in the backyard, about to mow the lawn, when a monarch butterfly flew over and landed on my finger.'
puts 'I asked him what he wanted.'
puts 'And he said:'
puts '"Bring back 80\'s speed metal."'
puts 'I truely feel like I was visited by an angel that day.'
